### ISSUE TITLE
Incorrect Bear Fact

### ISSUE THREAD

**Issue by stnevans** [jasmaa/stapler-kun#2]
"Of the eight bear species, four live in the Southern Hemisphere and four in the Northern Hemisphere"
This is not correct. In fact, all 8 species of bears have habitats that overlap the Northern Hemisphere. The spectacled bear is probably the most southern of the bears, but even its habitat ranges into northern Venezuela and Colombia, which is above the equator [1]. 

[1] https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Tremarctos_ornatus_distribution.svg/1024px-Tremarctos_ornatus_distribution.svg.png

**Comment by jasmaa** [comment]
Yeah I think this fact is just wrong (most of them are in the north). It should be removed.

https://www.britannica.com/animal/bear

![global-map-geographic-ranges-8-bear-species](https://user-images.githubusercontent.com/19419059/226607598-57b3c3ca-eebe-4c69-b7b5-c796dc65cf14.png)
